apiVersion: v1
kind: Service
metadata:
  name: reddit-service
# spec:
#   type: NodePort
spec:
  type: LoadBalancer
  selector:
    app: reddit  # Must match pod labels
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007